import { TASK } from "./features/types";

export const demoData = [
  createData(
    "task_dnafsdhnfailsudhfasuid",
    "A機能製造",
    "project_sdfnasidfuahs",
    "製造",
    "開始前",
    1,
    1,
    "2021-09-12",
    "2021-09-15",
    "2021-07-10",
    "2021-07-10",
    "user_assigned",
    "user_author",
    "テストデータA使用",
    "2021-07-10 12:00",
    "2021-07-10 12:00"
  ),
  createData(
    "task_dnafsdhnfailsudhfad",
    "B機能製造",
    "project_sdfnasidfuahs",
    "製造",
    "開始前",
    1,
    1,
    "2021-09-11",
    "2021-09-13",
    "2021-07-10",
    "2021-07-10",
    "user_assigned",
    "user_author",
    "テストデータA使用",
    "2021-07-10 12:00",
    "2021-07-10 12:00"
  ),
  createData(
    "task_dnafsdhnfailsfasuid",
    "C機能製造",
    "project_sdfnasidfuahs",
    "製造",
    "開始前",
    1,
    1,
    "2021-09-10",
    "2021-09-29",
    "2021-07-10",
    "2021-07-10",
    "user_assigned",
    "user_author",
    "テストデータA使用",
    "2021-07-10 12:00",
    "2021-07-10 12:00"
  ),
];

function createData(
  task_id: string,
  task_name: string,
  project_id: string,
  category: string,
  status: string,
  estimate_manhour: number,
  actual_manhour: number,
  scheduled_startdate: string,
  scheduled_enddate: string,
  actual_startdate: string,
  actual_enddate: string,
  assigned_id: string,
  author_id: string,
  description: string,
  created_at: string,
  update_at: string
): TASK {
  return {
    task_id: task_id,
    task_name: task_name,
    project_id: project_id,
    category_id: category,
    status: status,
    estimate_manhour: estimate_manhour,
    actual_manhour: actual_manhour,
    scheduled_startdate: scheduled_startdate,
    scheduled_enddate: scheduled_enddate,
    actual_startdate: actual_startdate,
    actual_enddate: actual_enddate,
    assigned_id: assigned_id,
    author_id: author_id,
    description: description,
    created_at: created_at,
    update_at: update_at,
  };
}
